### ISSUE TITLE
Create Proposal Form/Transaction Alpha

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#10]
## stage 1
- simple proposal form
  - expiration time, title, description, link, encoded action data
  - could put tribute token address, shares, loot, tribute amount and encode the actions from there.
- submit transaction 
  - polling
- view proposal
  - fetch proposal
 
 #### resources
 https://github.com/HausDAO/Baal/blob/feat/summonTask/test/BaalSafe.test.ts#L1515
 
 ```
     function submitProposal(
        bytes calldata proposalData,
        uint32 expiration,
        string calldata details
    ) 
 ```
 proposalData = encoded multisend action.
  - I am looking for some recipes here.
  - i guess it will need to approve baal to spend user's tokens for tribute, do an erc20 transfer from user to baal, an mint shares/loot to the user.
 
  expiration = epoch time in seconds
  https://www.epochconverter.com/
  
  details
  - we need to start defining our details schema. proposal type is going to be really important for the ui
    - proposalType, title, description, link ??
    - change link to contentURI
 

### Figma
details

https://www.twistedchickentenders.com/

form

https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=3013%3A17052
 
 #### question:
 - do we need a list with links to the proposal detail?
 
 ### stage 2 (break into another card)
 - sponsor
 - vote
 - execute

**Comment by earth2travis** [comment]
Polling system impacts SDK

**Comment by jonathanprozzi** [comment]
@jordanlesich @skuhlmann -- noticed this is in Done. Are we able to close the issue? Not sure I remember where we are with this, sorry!
