### ISSUE TITLE
Show and Tell: Radix UI and Stitches

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#20]
## What

Quick (informal) demo of Radix UI and Stitches to the group, showing off some basic use and what you've liked about it. This can be combined with Issue #21. 

## Todo

- Demo Radix (and possibly Stitches, if ready) inside the Summoner App
- Document the learnings from this session (if we can record)

**Comment by earth2travis** [comment]
Add links to https://github.com/HausDAO/daohaus-monorepo/wiki/Docs
