### ISSUE TITLE
Setup Storybook

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#22]
## What

- Rage to test out using Storybook in our component library package. We can compare the results from this and Ladle to see which we want to move forward with, and then add that to the `sage` monorepo in our component library package.

## Todo

- Add Storybook to the component library package in the Rage monorepo
- Add a few components and create stories for them
- Run the build process for Storybook

## Resources

- [Storybook](https://storybook.js.org/)
- [Storybook with nx](https://nx.dev/storybook/overview-react)

**Comment by jordanlesich** [comment]
I've got a few components fully built to spec and displayed through story book. 

Would be nice to review this pattern with JP and Rowdy and see if anything can be improved.

**Comment by 0xRowdy** [comment]
> 

That sounds great. Sometime tomorrow (4/4/22)?

**Comment by jonathanprozzi** [comment]
Storybook exists on the Rage repo. We have a separate card for the deploy: https://github.com/HausDAO/daohaus-rage/issues/46 so we can close this one out.

The Stories will be created as we build out the components in the component library.
