### ISSUE TITLE
Haus SDK Rage: Fetch support/library structure

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#25]
- Learn about making efficient cross chain queries on user address in the haus-sdk
  - explore graphql schema stitch
- Integrate cermaic basicprofile fetch in SDK
- Experiment with ORM style query building in SDK
  - getDaosByMember

- provide dao scoped queries
  - explore proposal hydration
    - action decoding
    - details parsing vs. in subgraph

- polling experiments
  - subscriptions

**Comment by earth2travis** [comment]
Do we need a rage report for this issue?

**Comment by skuhlmann** [comment]
some input for the lib structure:

https://nx.dev/structure/library-types

**Comment by skuhlmann** [comment]
> Found the Rage SDK here: https://github.com/HausDAO/daohaus-rage/tree/master/libs/haus-sdk

WIP rage report to present at show and tell friday
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?edit

**Comment by skuhlmann** [comment]
added here:
https://github.com/HausDAO/daohaus-monorepo/wiki/Rage#rage-reports
