### ISSUE TITLE
Deploy, Test and Create subgraph support for tribute escrow contract

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#27]
- [ ] Add contract events
- [ ] deploy rinkeby
- [ ] subgraph mappings on escrow contract
- [ ] cli test

## notes
- the proposal event should fire before one in the escrow, so we can add to that entity on escrow minion event
  - model after escrow minion
- we might want to clear or mark redeemed on a failed proposal
  - maybe an event on releaseEscrow so we can display a button to release

## resources

https://github.com/HausDAO/MinionSummonerV2/blob/main/contracts/EscrowMinion.sol

https://github.com/HausDAO/daohaus-supergraph/blob/master/src/escrow-minion-mapping.ts

**Comment by skuhlmann** [comment]
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?both

**Comment by earth2travis** [comment]
Sam's HackMD in the comment above has been moved to the WiKi [TributeEscrow](https://github.com/HausDAO/daohaus-monorepo/wiki/TributeEscrow)
