### ISSUE TITLE
Complete Storybook Tutorial

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#32]
Complete [Frontend Masters Design Systems With React and Storybook course](https://frontendmasters.com/courses/design-systems/)

## Champions

- [x] Jord
- [x] Travis

**Comment by jonathanprozzi** [comment]
## What

We want to make sure there's time for learning and skill building, so we're adding these as issues in the Rage monorepo. This is from our _Society of Champs_ course progression. 

Assign yourself if you're interested in being part of this. We'll determine how/when to share knowledge, but thinking of including weekly show and tell sessions (TBD).

### Tutorial 

- [Frontend Masters Design Systems With React and Storybook course](https://frontendmasters.com/courses/design-systems/)
- Goals from _Society of Champs_:
  - We didn't specify, but a good goal may be to build familiarity with Storybook structure 

### Challenge

- Watch the Frontend Masters course
- Begin adding Summoner components to the Rage component library and create Stories for them

**Comment by jordanlesich** [comment]
Finished. 

Watch the Frontend Masters course:
![Screenshot from 2022-04-06 14-58-27](https://user-images.githubusercontent.com/53406838/162078984-954a996a-77f9-4b98-9a9a-287247662d62.png)

And did a PR for Input, ToolTip, Wrapper, etc

https://github.com/HausDAO/daohaus-rage/pull/47

In retrospect, I should have watched all of the course first as there were a lot of good patterns and hints I could have used in implementing storybook. Taking the course also highlighted some ways we could make improve theming, Story book docs, and Raging with Redux to implement theme state changes.

**Comment by earth2travis** [comment]
<img width="608" alt="completed" src="https://user-images.githubusercontent.com/522182/163746864-a05dff03-3f9f-4463-8e74-23fd1d444908.png">

**Comment by earth2travis** [comment]
## [Design Systems](https://fem-design-systems.netlify.app/)

### Pillars

- Design Language
- Component Library
- Style Guide

### [Building](https://fem-design-systems.netlify.app/building-a-design-system)

1. Define your design principles
2. Conduct a UI audit
3. Create your checklist
4. Define your workflows

**Comment by earth2travis** [comment]
### [Prioritizing Components](https://fem-design-systems.netlify.app/building-a-design-system)

- Does this request embody our design principles?
- Does this requires require a lot of design/development effort?
- Does this request come with a high risk to the success of our product?
- Does this request coincide with our product roadmap?
- Does this request require a lot of maintenance?
- Does this request improve the user experience of our products?
- Are we confident in this request or will it need to be revisited again in the near future?
- Is this request technically feasible?

![calculating-priority](https://i.imgur.com/31iDKQq.jpg)

Do we need to create a survey to determine how we should prioritize components?

**Comment by earth2travis** [comment]
### [Checklist](https://fem-design-systems.netlify.app/design-system-checklist)

May be good to include these checklist items in the issue template as design and development tasks.

**Comment by earth2travis** [comment]
## Exercises

Could not do the Button Variations exercise. Was getting an error installing `styled-components-modifiers`. Assuming it is not supported in `"styled-components": "^5.3.5"`

[Styled Map](https://www.npmjs.com/package/styled-map) may be an alternative

Rolled back to `"styled-components": "^4.4.1"` and was able to install `styled-components-modifiers`

**Comment by earth2travis** [comment]
### Ad-ons

Got kinda lost in the [Using addons](https://fem-design-systems.netlify.app/using-addons) section.

Seems like a lot of the add-ons she installed are now included by default.

#### Pre-installed

- [Docs](https://storybook.js.org/addons/@storybook/addon-docs/)
- [Actions](https://storybook.js.org/addons/@storybook/addon-actions/)
- [Controls](https://storybook.js.org/addons/@storybook/addon-controls/)

- Make sure Docs are added for each component. Who writes this? Wen?
- These Docs should also be reviewed in the Review stage

#### [Using themes](https://fem-design-systems.netlify.app/using-themes)

[@storybook/addon-contexts](https://storybook.js.org/addons/@storybook/addon-contexts/)

How do these contexts related to:

![change-background](https://i.imgur.com/eAcHnBR.png)

#### Accessibility

- [a11y](https://storybook.js.org/addons/@storybook/addon-a11y/)

Should include a step in Review to review the Accessibility tab.

#### Decrecated

- [Knobs](https://storybook.js.org/addons/@storybook/addon-knobs/)

What other add-ons do we need?

**Comment by jonathanprozzi** [comment]
> ### [Checklist](https://fem-design-systems.netlify.app/design-system-checklist)
> May be good to include these checklist items in the issue template as design and development tasks.

I like this. I think including _Accessibility_ at the very least is a good thing for us to be aware of!

**Comment by jonathanprozzi** [comment]
> ## Exercises
> Could not do the Button Variations exercise. Was getting an error installing `styled-components-modifiers`. Assuming it is not supported in `"styled-components": "^5.3.5"`
> 
> [Styled Map](https://www.npmjs.com/package/styled-map) may be an alternative
> 
> Rolled back to `"styled-components": "^4.4.1"` and was able to install `styled-components-modifiers`

Interesting -- that package looks like it's not been maintained for awhile. It seems to allow for BEM modifiers which is pretty neat. We can probably structure things like that on our own if we wanted since styled-components seems to allow some of this out of the box now.

**Comment by jonathanprozzi** [comment]
Yup! A lot of these have been built into Storybook's core at this point. We should consider leveraging the a11y testing in the future, and we can also use Cypress testing for this!

**Comment by jonathanprozzi** [comment]
> 

I think these are great questions. I'm not sure we're at the point where we need a survey, but I think that if this becomes a large enough library where it's a product in itself (and I agree we should treat it as that now) we may want to do this. For now we should focus on adding our backlog of atoms and molecules and then go from there. 

Our process for adding components is largely determined by pragmatic use at this point -- we're adding the ones we're building as we go and dogfooding the library. That said, this is a great list for us to consider. @jordanlesich @earth2travis thoughts?

**Comment by earth2travis** [comment]
Sounds great to me. We can just build them as needed based on the molecules and atoms in flows we are developing
