### ISSUE TITLE
Use absolute paths instead of relative paths

### ISSUE THREAD

**Issue by alexkeating** [HausDAO/daohaus-rage#37]
- Currently we are using relative imports in our apps in libraries we should explore using absolute imports

**Comment by earth2travis** [comment]
@alexkeating can you please add some additional context to this issue. Why is this important and what need to be done?

**Comment by earth2travis** [comment]
Closing this issue based on conversation in this mornings [Planning](https://github.com/HausDAO/daohaus-monorepo/wiki/Planning%3A-June-13%2C-2022/) meeting. The path ship has sailed
