### ISSUE TITLE
Complete Redux Tutorial

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#38]
## What

We want to make sure there's time for learning and skill building, so we're adding these as issues in the Rage monorepo. This is from our _Society of Champs_ course progression. 

Assign yourself if you're interested in being part of this. We'll determine how/when to share knowledge, but thinking of including weekly show and tell sessions (TBD).

### Tutorial 

- [Frontend Masters Redux Fundamentals Course](https://frontendmasters.com/courses/redux-fundamentals/)
- Goals from _Society of Champs_:
- Knows how Redux and Redux Toolkit work under the hood
- Can effectively model and create state reducers, thunks, actions, and middleware

### Challenge

- Watch the Frontend Masters course
- Undecided challenge -- aim to become comfortable with the goals

**Comment by jordanlesich** [comment]
We can retire this. I don't think Redux made the cut

**Comment by jonathanprozzi** [comment]
Totally. Thanks for flagging this @jordanlesich
