### ISSUE TITLE
Setup Monorepo Configuration for Proper Internal Package Dependencies

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#49]
## What

I have been raging on breaking up the SDK package into multiple data-access and utility libraries and ran into build issues when a package is included in an app and that package imports another our our packages.

If there is some manual configuration outside the nx generators we will want to document that as well.

### Details

1. playground react app imports the haus-sdk-rage library:

https://github.com/HausDAO/daohaus-rage/blob/rage/sdk/apps/sdk-playground/src/app/App.tsx#L5

2. haus-sdk-rage library imports constant from haus-parlor library

https://github.com/HausDAO/daohaus-rage/blob/rage/sdk/libs/haus-sdk-rage/src/utils/requests.ts#L5

- note that in the latest commit i've commented out the import and moved the constant into haus-sdk-rage just to get it to work
-  this works perfectly when running just the haus-sdk-rage library (in tests at least)

3. this breaks when running the playground app

`nx serve sdk-playground`

![Screenshot from 2022-04-06 16-28-41](https://user-images.githubusercontent.com/6923345/162242350-581d52f9-dc06-4955-b477-08197c7c07e4.png)

### Potential resources

https://github.com/nrwl/nx/issues/602#issuecomment-560451015

https://nx.dev/structure/buildable-and-publishable-libraries

https://nx.dev/structure/monorepo-tags

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-rage/commit/5092ef4dcbda1c7dd9e5161fbdc627797a21125b

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-rage/pull/54

**Comment by jonathanprozzi** [comment]
@alexkeating looks like we can close this since it's merged into Done?
