### ISSUE TITLE
Create Alpha CLI

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#7]
- baal repo hardhat tasks
- suite of tasks to deploy daos and interact with daos
- docs page to outline the commands.

**Comment by earth2travis** [comment]
Should we consider adding docs related to this?

**Comment by earth2travis** [comment]
[Baal CLI Rage Report](https://hackmd.io/@daohaus/B1IltXsmc)

**Comment by earth2travis** [comment]
@dekanbro any progress on getting this commands defined?

**Comment by earth2travis** [comment]
https://github.com/HausDAO/Baal/blob/feat/baalZodiac/hardhat.config.ts

**Comment by earth2travis** [comment]
Docs: https://baal-docs.vercel.app/baal-cli

**Comment by earth2travis** [comment]
Implement admin features through Shamans

**Comment by earth2travis** [comment]
Some dependencies on contract updates

**Comment by skuhlmann** [comment]
This is done to the point we need it now. If more reqs come up we can open new tickets.
