### ISSUE TITLE
Create Summon Alpha Rage Report

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#9]
## What

Create a _Rage Report_ for the Summoner App and share with the team.

## Todo

- Create _Rage Report_  - Jord

## Resources

- [Rage Report: Summoner](https://hackmd.io/SLJNR5VoSzGlrJPN1_DnqA)
 - @jordanlesich I added your report to this

**Comment by earth2travis** [comment]
https://hackmd.io/SLJNR5VoSzGlrJPN1_DnqA
